install! 'cocoapods', :deterministic_uuids => false

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Sijoitussimulaattori' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sijoitussimulaattori
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTWebSocket',
    'RCTImage'
    # Add any other subspecs you want to use in your project
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNLanguages', :path => '../node_modules/react-native-languages'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'GoogleAppMeasurement', '~> 5.3.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  pod 'Firebase/Auth'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'SijoitussimulaattoriTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Sijoitussimulaattori-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sijoitussimulaattori-tvOS

  target 'Sijoitussimulaattori-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
