# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Sijoitussimulaattori' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sijoitussimulaattori
  pod 'GoogleAppMeasurement', '= 5.2.0'
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNLanguages', :path => '../node_modules/react-native-languages'

  target 'SijoitussimulaattoriTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Sijoitussimulaattori-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sijoitussimulaattori-tvOS

  target 'Sijoitussimulaattori-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
